window.UNICODE_SYMBOLS = [
  { char: '•', name: 'Bullet', category: 'Punctuation', keywords: ['bullet', 'list', 'dot'] },
  { char: '·', name: 'Middle dot', category: 'Punctuation', keywords: ['dot', 'middle', 'interpunct'] },
  { char: '…', name: 'Ellipsis', category: 'Punctuation', keywords: ['ellipsis', 'more', 'three dots'] },
  { char: '—', name: 'Em dash', category: 'Punctuation', keywords: ['em dash', 'dash', 'long dash'] },
  { char: '–', name: 'En dash', category: 'Punctuation', keywords: ['en dash', 'dash', 'short dash'] },
  { char: '“', name: 'Left double quote', category: 'Punctuation', keywords: ['quote', 'double quote', 'opening quote'] },
  { char: '”', name: 'Right double quote', category: 'Punctuation', keywords: ['quote', 'double quote', 'closing quote'] },
  { char: '‘', name: 'Left single quote', category: 'Punctuation', keywords: ['quote', 'single quote', 'opening quote'] },
  { char: '’', name: 'Right single quote', category: 'Punctuation', keywords: ['quote', 'single quote', 'closing quote'] },
  { char: '«', name: 'Left guillemet', category: 'Punctuation', keywords: ['quote', 'angle quote', 'guillemet'] },
  { char: '»', name: 'Right guillemet', category: 'Punctuation', keywords: ['quote', 'angle quote', 'guillemet'] },
  { char: '¿', name: 'Inverted question mark', category: 'Punctuation', keywords: ['question', 'inverted', 'spanish'] },
  { char: '¡', name: 'Inverted exclamation mark', category: 'Punctuation', keywords: ['exclamation', 'inverted', 'spanish'] },
  { char: '§', name: 'Section sign', category: 'Punctuation', keywords: ['section', 'paragraph', 'law'] },
  { char: '¶', name: 'Pilcrow', category: 'Punctuation', keywords: ['pilcrow', 'paragraph', 'mark'] },
  { char: '†', name: 'Dagger', category: 'Punctuation', keywords: ['dagger', 'footnote'] },
  { char: '‡', name: 'Double dagger', category: 'Punctuation', keywords: ['double dagger', 'footnote'] },
  { char: '°', name: 'Degree sign', category: 'Punctuation', keywords: ['degree', 'temperature', 'angle'] },
  { char: '′', name: 'Prime', category: 'Punctuation', keywords: ['prime', 'minutes', 'feet'] },
  { char: '″', name: 'Double prime', category: 'Punctuation', keywords: ['double prime', 'seconds', 'inches'] },
  { char: '※', name: 'Reference mark', category: 'Punctuation', keywords: ['reference', 'mark', 'asterism'] },
  { char: '№', name: 'Numero sign', category: 'Punctuation', keywords: ['number', 'numero', 'no'] },
  { char: '↩', name: 'Left arrow with hook', category: 'Arrows', keywords: ['return', 'back', 'undo'] },
  { char: '↪', name: 'Right arrow with hook', category: 'Arrows', keywords: ['reply', 'forward', 'hook'] },
  { char: '←', name: 'Left arrow', category: 'Arrows', keywords: ['left', 'back', 'arrow'] },
  { char: '↑', name: 'Up arrow', category: 'Arrows', keywords: ['up', 'arrow'] },
  { char: '→', name: 'Right arrow', category: 'Arrows', keywords: ['right', 'forward', 'arrow'] },
  { char: '↓', name: 'Down arrow', category: 'Arrows', keywords: ['down', 'arrow'] },
  { char: '↔', name: 'Left right arrow', category: 'Arrows', keywords: ['horizontal', 'left right', 'bidirectional'] },
  { char: '↕', name: 'Up down arrow', category: 'Arrows', keywords: ['vertical', 'up down', 'bidirectional'] },
  { char: '↖', name: 'North west arrow', category: 'Arrows', keywords: ['north west', 'up left'] },
  { char: '↗', name: 'North east arrow', category: 'Arrows', keywords: ['north east', 'up right'] },
  { char: '↘', name: 'South east arrow', category: 'Arrows', keywords: ['south east', 'down right'] },
  { char: '↙', name: 'South west arrow', category: 'Arrows', keywords: ['south west', 'down left'] },
  { char: '⇒', name: 'Double right arrow', category: 'Arrows', keywords: ['implies', 'right', 'double'] },
  { char: '⇐', name: 'Double left arrow', category: 'Arrows', keywords: ['left', 'double'] },
  { char: '⇑', name: 'Double up arrow', category: 'Arrows', keywords: ['up', 'double'] },
  { char: '⇓', name: 'Double down arrow', category: 'Arrows', keywords: ['down', 'double'] },
  { char: '⇔', name: 'Double left right arrow', category: 'Arrows', keywords: ['iff', 'double', 'bidirectional'] },
  { char: '↦', name: 'Maps to', category: 'Arrows', keywords: ['maps to', 'function', 'arrow'] },
  { char: '↺', name: 'Counterclockwise arrow', category: 'Arrows', keywords: ['refresh', 'rotate', 'counterclockwise'] },
  { char: '↻', name: 'Clockwise arrow', category: 'Arrows', keywords: ['reload', 'rotate', 'clockwise'] },
  { char: '➜', name: 'Heavy arrow', category: 'Arrows', keywords: ['arrow', 'forward', 'heavy'] },
  { char: '➤', name: 'Black right arrow', category: 'Arrows', keywords: ['arrow', 'right', 'black'] },
  { char: '±', name: 'Plus minus', category: 'Math', keywords: ['plus minus', 'plus', 'minus'] },
  { char: '×', name: 'Multiplication', category: 'Math', keywords: ['multiply', 'times'] },
  { char: '÷', name: 'Division', category: 'Math', keywords: ['divide', 'division'] },
  { char: '≈', name: 'Approximately equal', category: 'Math', keywords: ['approx', 'approximately', 'equal'] },
  { char: '≠', name: 'Not equal', category: 'Math', keywords: ['not equal', 'inequality'] },
  { char: '≤', name: 'Less than or equal', category: 'Math', keywords: ['less than or equal', 'lte'] },
  { char: '≥', name: 'Greater than or equal', category: 'Math', keywords: ['greater than or equal', 'gte'] },
  { char: '∞', name: 'Infinity', category: 'Math', keywords: ['infinity', 'endless'] },
  { char: '∑', name: 'Summation', category: 'Math', keywords: ['sum', 'summation'] },
  { char: '∏', name: 'Product', category: 'Math', keywords: ['product', 'pi'] },
  { char: '∫', name: 'Integral', category: 'Math', keywords: ['integral', 'calculus'] },
  { char: '√', name: 'Square root', category: 'Math', keywords: ['square root', 'root'] },
  { char: '∛', name: 'Cube root', category: 'Math', keywords: ['cube root', 'root'] },
  { char: '∜', name: 'Fourth root', category: 'Math', keywords: ['fourth root', 'root'] },
  { char: '∂', name: 'Partial derivative', category: 'Math', keywords: ['partial', 'derivative'] },
  { char: '∇', name: 'Nabla', category: 'Math', keywords: ['gradient', 'nabla'] },
  { char: '∅', name: 'Empty set', category: 'Math', keywords: ['empty set', 'null', 'zero'] },
  { char: '∈', name: 'Element of', category: 'Math', keywords: ['element', 'belongs to', 'set'] },
  { char: '∉', name: 'Not element of', category: 'Math', keywords: ['not element', 'set'] },
  { char: '∩', name: 'Intersection', category: 'Math', keywords: ['intersection', 'set'] },
  { char: '∪', name: 'Union', category: 'Math', keywords: ['union', 'set'] },
  { char: '∧', name: 'Logical and', category: 'Math', keywords: ['and', 'logic'] },
  { char: '∨', name: 'Logical or', category: 'Math', keywords: ['or', 'logic'] },
  { char: '⊕', name: 'Circled plus', category: 'Math', keywords: ['circled plus', 'xor'] },
  { char: '⊗', name: 'Circled times', category: 'Math', keywords: ['circled times', 'tensor'] },
  { char: '⊂', name: 'Subset', category: 'Math', keywords: ['subset', 'set'] },
  { char: '⊃', name: 'Superset', category: 'Math', keywords: ['superset', 'set'] },
  { char: '⊆', name: 'Subset or equal', category: 'Math', keywords: ['subset or equal'] },
  { char: '⊇', name: 'Superset or equal', category: 'Math', keywords: ['superset or equal'] },
  { char: '⊥', name: 'Perpendicular', category: 'Math', keywords: ['perpendicular', 'orthogonal'] },
  { char: '∠', name: 'Angle', category: 'Math', keywords: ['angle', 'geometry'] },
  { char: '⌈', name: 'Ceiling left', category: 'Math', keywords: ['ceiling', 'bracket'] },
  { char: '⌉', name: 'Ceiling right', category: 'Math', keywords: ['ceiling', 'bracket'] },
  { char: '⌊', name: 'Floor left', category: 'Math', keywords: ['floor', 'bracket'] },
  { char: '⌋', name: 'Floor right', category: 'Math', keywords: ['floor', 'bracket'] },
  { char: '★', name: 'Black star', category: 'Shapes', keywords: ['star', 'favorite', 'black'] },
  { char: '☆', name: 'White star', category: 'Shapes', keywords: ['star', 'outline', 'favorite'] },
  { char: '●', name: 'Black circle', category: 'Shapes', keywords: ['circle', 'bullet', 'dot'] },
  { char: '○', name: 'White circle', category: 'Shapes', keywords: ['circle', 'outline'] },
  { char: '■', name: 'Black square', category: 'Shapes', keywords: ['square', 'bullet'] },
  { char: '□', name: 'White square', category: 'Shapes', keywords: ['square', 'outline'] },
  { char: '▲', name: 'Black up triangle', category: 'Shapes', keywords: ['triangle', 'up'] },
  { char: '△', name: 'White up triangle', category: 'Shapes', keywords: ['triangle', 'outline'] },
  { char: '◆', name: 'Black diamond', category: 'Shapes', keywords: ['diamond', 'bullet'] },
  { char: '◇', name: 'White diamond', category: 'Shapes', keywords: ['diamond', 'outline'] },
  { char: '♥', name: 'Black heart', category: 'Shapes', keywords: ['heart', 'love'] },
  { char: '♡', name: 'White heart', category: 'Shapes', keywords: ['heart', 'outline', 'love'] },
  { char: '♠', name: 'Spade', category: 'Shapes', keywords: ['spade', 'cards'] },
  { char: '♣', name: 'Club', category: 'Shapes', keywords: ['club', 'cards'] },
  { char: '☀', name: 'Sun', category: 'Shapes', keywords: ['sun', 'weather'] },
  { char: '☁', name: 'Cloud', category: 'Shapes', keywords: ['cloud', 'weather'] },
  { char: '☂', name: 'Umbrella', category: 'Shapes', keywords: ['umbrella', 'weather'] },
  { char: '☃', name: 'Snowman', category: 'Shapes', keywords: ['snowman', 'weather', 'winter'] },
  { char: '☕', name: 'Hot beverage', category: 'Shapes', keywords: ['coffee', 'tea', 'cup'] },
  { char: '☎', name: 'Telephone', category: 'Shapes', keywords: ['phone', 'call'] },
  { char: '⚑', name: 'Flag', category: 'Shapes', keywords: ['flag', 'marker'] },
  { char: '⚠', name: 'Warning', category: 'Shapes', keywords: ['warning', 'caution', 'alert'] },
  { char: '✓', name: 'Check mark', category: 'Shapes', keywords: ['check', 'tick', 'done'] },
  { char: '✔', name: 'Heavy check mark', category: 'Shapes', keywords: ['check', 'tick', 'done'] },
  { char: '✕', name: 'Multiplication x', category: 'Shapes', keywords: ['x', 'close', 'cancel'] },
  { char: '✖', name: 'Heavy multiplication x', category: 'Shapes', keywords: ['x', 'close', 'cancel'] },
  { char: '✚', name: 'Heavy plus', category: 'Shapes', keywords: ['plus', 'add'] },
  { char: '✦', name: 'Black four pointed star', category: 'Shapes', keywords: ['star', 'sparkle'] },
  { char: '✧', name: 'White four pointed star', category: 'Shapes', keywords: ['star', 'sparkle'] },
  { char: '✉', name: 'Envelope', category: 'Shapes', keywords: ['mail', 'email'] },
  { char: '✨', name: 'Sparkles', category: 'Shapes', keywords: ['sparkles', 'magic'] },
  { char: '⌘', name: 'Command', category: 'Shapes', keywords: ['command', 'meta', 'mac'] },
  { char: '⏎', name: 'Return', category: 'Shapes', keywords: ['return', 'enter', 'newline'] },
  { char: '⌫', name: 'Delete left', category: 'Shapes', keywords: ['backspace', 'delete'] },
  { char: '$', name: 'Dollar sign', category: 'Currency', keywords: ['dollar', 'money'] },
  { char: '€', name: 'Euro sign', category: 'Currency', keywords: ['euro', 'money'] },
  { char: '£', name: 'Pound sign', category: 'Currency', keywords: ['pound', 'sterling', 'money'] },
  { char: '¥', name: 'Yen sign', category: 'Currency', keywords: ['yen', 'money'] },
  { char: '₹', name: 'Rupee sign', category: 'Currency', keywords: ['rupee', 'money', 'india'] },
  { char: '₩', name: 'Won sign', category: 'Currency', keywords: ['won', 'money', 'korea'] },
  { char: '₽', name: 'Ruble sign', category: 'Currency', keywords: ['ruble', 'money'] },
  { char: '₺', name: 'Lira sign', category: 'Currency', keywords: ['lira', 'money'] },
  { char: '₫', name: 'Dong sign', category: 'Currency', keywords: ['dong', 'money'] },
  { char: '₴', name: 'Hryvnia sign', category: 'Currency', keywords: ['hryvnia', 'money'] },
  { char: '₦', name: 'Naira sign', category: 'Currency', keywords: ['naira', 'money'] },
  { char: '₪', name: 'Shekel sign', category: 'Currency', keywords: ['shekel', 'money'] },
  { char: '₿', name: 'Bitcoin sign', category: 'Currency', keywords: ['bitcoin', 'crypto'] },
  { char: '¢', name: 'Cent sign', category: 'Currency', keywords: ['cent', 'money'] },
  { char: '½', name: 'One half', category: 'Fractions', keywords: ['half', 'fraction'] },
  { char: '¼', name: 'One quarter', category: 'Fractions', keywords: ['quarter', 'fraction'] },
  { char: '¾', name: 'Three quarters', category: 'Fractions', keywords: ['three quarters', 'fraction'] },
  { char: '⅓', name: 'One third', category: 'Fractions', keywords: ['third', 'fraction'] },
  { char: '⅔', name: 'Two thirds', category: 'Fractions', keywords: ['third', 'fraction'] },
  { char: '⅛', name: 'One eighth', category: 'Fractions', keywords: ['eighth', 'fraction'] },
  { char: '⅜', name: 'Three eighths', category: 'Fractions', keywords: ['eighth', 'fraction'] },
  { char: '⅝', name: 'Five eighths', category: 'Fractions', keywords: ['eighth', 'fraction'] },
  { char: '⅞', name: 'Seven eighths', category: 'Fractions', keywords: ['eighth', 'fraction'] },
  { char: 'α', name: 'Alpha', category: 'Greek', keywords: ['alpha', 'greek'] },
  { char: 'β', name: 'Beta', category: 'Greek', keywords: ['beta', 'greek'] },
  { char: 'γ', name: 'Gamma', category: 'Greek', keywords: ['gamma', 'greek'] },
  { char: 'δ', name: 'Delta', category: 'Greek', keywords: ['delta', 'greek'] },
  { char: 'ε', name: 'Epsilon', category: 'Greek', keywords: ['epsilon', 'greek'] },
  { char: 'ζ', name: 'Zeta', category: 'Greek', keywords: ['zeta', 'greek'] },
  { char: 'η', name: 'Eta', category: 'Greek', keywords: ['eta', 'greek'] },
  { char: 'θ', name: 'Theta', category: 'Greek', keywords: ['theta', 'greek'] },
  { char: 'ι', name: 'Iota', category: 'Greek', keywords: ['iota', 'greek'] },
  { char: 'κ', name: 'Kappa', category: 'Greek', keywords: ['kappa', 'greek'] },
  { char: 'λ', name: 'Lambda', category: 'Greek', keywords: ['lambda', 'greek'] },
  { char: 'μ', name: 'Mu', category: 'Greek', keywords: ['mu', 'greek'] },
  { char: 'ν', name: 'Nu', category: 'Greek', keywords: ['nu', 'greek'] },
  { char: 'ξ', name: 'Xi', category: 'Greek', keywords: ['xi', 'greek'] },
  { char: 'ο', name: 'Omicron', category: 'Greek', keywords: ['omicron', 'greek'] },
  { char: 'π', name: 'Pi', category: 'Greek', keywords: ['pi', 'greek'] },
  { char: 'ρ', name: 'Rho', category: 'Greek', keywords: ['rho', 'greek'] },
  { char: 'σ', name: 'Sigma', category: 'Greek', keywords: ['sigma', 'greek'] },
  { char: 'τ', name: 'Tau', category: 'Greek', keywords: ['tau', 'greek'] },
  { char: 'υ', name: 'Upsilon', category: 'Greek', keywords: ['upsilon', 'greek'] },
  { char: 'φ', name: 'Phi', category: 'Greek', keywords: ['phi', 'greek'] },
  { char: 'χ', name: 'Chi', category: 'Greek', keywords: ['chi', 'greek'] },
  { char: 'ψ', name: 'Psi', category: 'Greek', keywords: ['psi', 'greek'] },
  { char: 'ω', name: 'Omega', category: 'Greek', keywords: ['omega', 'greek'] },
  { char: 'Δ', name: 'Delta capital', category: 'Greek', keywords: ['delta', 'capital', 'greek'] },
  { char: 'Λ', name: 'Lambda capital', category: 'Greek', keywords: ['lambda', 'capital', 'greek'] },
  { char: 'Π', name: 'Pi capital', category: 'Greek', keywords: ['pi', 'capital', 'greek'] },
  { char: 'Σ', name: 'Sigma capital', category: 'Greek', keywords: ['sigma', 'capital', 'greek'] },
  { char: 'Φ', name: 'Phi capital', category: 'Greek', keywords: ['phi', 'capital', 'greek'] },
  { char: 'Ω', name: 'Omega capital', category: 'Greek', keywords: ['omega', 'capital', 'greek'] }
];

